--DROP TABLE CUSTOMER_INFO;
--DROP TABLE PRODUCT_INFO;
--DROP TABLE ORDER_INFO;
--DROP TABLE PAY_INFO;
--DROP TABLE REFUND_INFO;

-- 고객정보
CREATE TABLE CUSTOMER_INFO(
        CUSTOMER_NUM CHAR(30),
        CUSTOMER_GR CHAR(30),
        SUB_DATE TIMESTAMP,
        FINAL_VISIT TIMESTAMP,
        SELF_VERFICATION VARCHAR2(50),
        SEX CHAR(10),
        AGE VARCHAR2(10),
        ADDRESS_ROAD VARCHAR2(500),
        ADDRESS_NUM VARCHAR2(500)
        );

-- 상품정보        
CREATE TABLE PRODUCT_INFO(
        PRODUCT_NUM VARCHAR2(50),
        PRODUCT_NAME VARCHAR2(300),
        COMPANY_NAME VARCHAR2(300),
        CATEGORY_NAME VARCHAR2(300),
        BRAND_NAME VARCHAR2(100),
        PRODUCT_CLASS VARCHAR2(100),
        REP_SELL_PRICE VARCHAR2(100),
        DELIVERY_COST VARCHAR2(100),
        SALES_STAT VARCHAR2(100),
        EXHIBIT_STAT CHAR(50)
        );

--주문정보        
CREATE TABLE ORDER_INFO(
        ORDER_NUM VARCHAR2(40),
        ORDER_SEQ VARCHAR2(40),
        ORDER_DATE TIMESTAMP,
        ORDER_CLASS VARCHAR2(30),
        ADDRESS VARCHAR2(200),
        PRODUCT_NUM VARCHAR2(30),
        PRODUCT_NAME VARCHAR2(300),
        OPCTION_NAME VARCHAR2(300),
        ORDER_QTY VARCHAR2(40),
        SELL_PRICE VARCHAR2(40),
        DELIVERY_COST VARCHAR2(40),
        COUPON_DISCOUNT VARCHAR2(40),
        CUSTOMER_ORDER CHAR(30),
        CUSTOMER_NUM CHAR(40)
        );
        
---- 결제정보
--CREATE TABLE PAY_INFO(
--        ORDER_NUM VARCHAR2(40),
--        PAY_NUM VARCHAR2(40),
--        PAY_DATE TIMESTAMP,
--        ORDER_CLASS_NAME VARCHAR2(30),
--        PAY_METHOD VARCHAR2(50),
--        PAY_AMOUNT VARCHAR2(40),
--        CARD_COMPANY VARCHAR2(30),
--        PAY_MONTH VARCHAR2(40)
--        );
--        
---- 환불정보
--CREATE TABLE REFUND_INFO(
--        ORDER_NUM VARCHAR2(40),
--        REFUND_NUM VARCHAR2(10),
--        REFUND_CLASS VARCHAR2(10),
--        PAY_METHOD VARCHAR2(50),
--        REFUND_AMOUNT VARCHAR2(20),
--        REFUND_MONTH VARCHAR2(10),
--        REFUND_DATE TIMESTAMP
--        );   